# Generated by Django 5.2.1 on 2025-06-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaders", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[("자격증", "자격증"), ("경력증명서", "경력증명서")],
                        max_length=30,
                        verbose_name="증명서 유형",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="certificates/", verbose_name="파일"),
                ),
                (
                    "leader_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="leaders.leaderapplication",
                        verbose_name="리더 신청서",
                    ),
                ),
            ],
        ),
    ]
