# Generated by Django 5.2.1 on 2025-06-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaders", "0003_leadercertificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadercertificate",
            name="file",
        ),
        migrations.AddField(
            model_name="leaderapplication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="처리일시"),
        ),
    ]
