# Generated by Django 5.2.1 on 2025-06-17 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaders", "0004_remove_leadercertificate_file_and_more"),
        ("upload", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadercertificate",
            name="file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.file",
                verbose_name="파일",
            ),
        ),
    ]
