# Generated by Django 5.2.1 on 2025-06-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaders", "0004_leaderapplication_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadercertificate",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="certificates/", verbose_name="파일"
            ),
        ),
    ]
