# Generated by Django 5.2.1 on 2025-06-17 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaders", "0005_leadercertificate_file"),
        ("upload", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadercertificate",
            name="file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.file",
                verbose_name="파일",
            ),
            preserve_default=False,
        ),
    ]
