# Generated by Django 5.2.1 on 2025-06-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaders", "0006_alter_leadercertificate_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PreviousActivity",
        ),
    ]
