# Generated by Django 5.2.1 on 2025-06-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaders", "0007_delete_previousactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderapplication",
            name="certificate_type",
            field=models.JSONField(blank=True, null=True, verbose_name="자격증 종류"),
        ),
    ]
