# Generated by Django 5.2.1 on 2025-06-11 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.IntegerField(help_text="나이대: 10, 20, 30 ...")),
            ],
            options={
                "verbose_name": "연령대",
                "verbose_name_plural": "연령대 목록",
                "ordering": ["group"],
                "indexes": [
                    models.Index(fields=["group"], name="options_age_group_8f2923_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리 목록",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["category_name"], name="options_cat_categor_ed1d1a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DigitalLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "디지털 역량 수준",
                "verbose_name_plural": "디지털 수준 목록",
                "ordering": ["level"],
                "indexes": [
                    models.Index(fields=["level"], name="options_dig_level_dd268d_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "관심 분야",
                "verbose_name_plural": "관심 분야 목록",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["interest_name"], name="options_int_interes_e998cb_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(max_length=100)),
                (
                    "depth",
                    models.CharField(
                        help_text="지역 유형: 시, 구, 동 등", max_length=10
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="options.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "지역",
                "verbose_name_plural": "지역 목록",
                "ordering": ["area_name"],
                "indexes": [
                    models.Index(fields=["depth"], name="options_are_depth_f7822c_idx")
                ],
            },
        ),
    ]
