# Generated by Django 5.2.1 on 2025-06-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["id"],
                "verbose_name": "지역",
                "verbose_name_plural": "지역 목록",
            },
        ),
    ]
