# Generated by Django 5.2.1 on 2025-06-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agegroup",
            options={
                "ordering": ["group"],
                "verbose_name": "연령대",
                "verbose_name_plural": "연령대 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["area_name"],
                "verbose_name": "지역",
                "verbose_name_plural": "지역 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="digitallevel",
            options={
                "ordering": ["level"],
                "verbose_name": "디지털 역량 수준",
                "verbose_name_plural": "디지털 수준 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="interest",
            options={
                "ordering": ["id"],
                "verbose_name": "관심 분야",
                "verbose_name_plural": "관심 분야 목록",
            },
        ),
        migrations.RenameField(
            model_name="area",
            old_name="name",
            new_name="area_name",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category_name",
        ),
        migrations.RenameField(
            model_name="interest",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="area",
            name="depth",
        ),
        migrations.AddField(
            model_name="area",
            name="area_type",
            field=models.CharField(
                default=1, help_text="지역 유형: 시, 구, 동 등", max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="agegroup",
            index=models.Index(fields=["group"], name="options_age_group_8f2923_idx"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["area_type"], name="options_are_area_ty_38e229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["category_name"], name="options_cat_categor_ed1d1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="digitallevel",
            index=models.Index(fields=["level"], name="options_dig_level_dd268d_idx"),
        ),
        migrations.AddIndex(
            model_name="interest",
            index=models.Index(fields=["title"], name="options_int_title_08fcc1_idx"),
        ),
    ]
