# Generated by Django 5.2.1 on 2025-06-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0002_alter_agegroup_options_alter_area_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="interest",
            name="options_int_title_08fcc1_idx",
        ),
        migrations.RenameField(
            model_name="interest",
            old_name="title",
            new_name="interest_name",
        ),
        migrations.AddIndex(
            model_name="interest",
            index=models.Index(
                fields=["interest_name"], name="options_int_interes_e998cb_idx"
            ),
        ),
    ]
