# Generated by Django 5.2.1 on 2025-06-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0003_remove_interest_options_int_title_08fcc1_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="area",
            name="options_are_area_ty_38e229_idx",
        ),
        migrations.RenameField(
            model_name="area",
            old_name="area_type",
            new_name="depth",
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["depth"], name="options_are_depth_f7822c_idx"),
        ),
    ]
