# Generated by Django 5.2.1 on 2025-06-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=50, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="이름"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="닉네임"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="생년월일"),
                ),
                (
                    "provider",
                    models.PositiveSmallIntegerField(default=0, verbose_name="제공자"),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(default=1, verbose_name="권한"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 로그인"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="계정 활성화"),
                ),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저 목록",
                "db_table": "user",
            },
        ),
    ]
