# Generated by Django 5.2.1 on 2025-06-05 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0001_initial"),
        ("upload", "0005_file_user_alter_file_thumbnail"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="options.area",
                verbose_name="지역",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="digital_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="options.digitallevel",
                verbose_name="디지털 레벨",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="upload.file",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="interest",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="options.interest",
                verbose_name="관심사",
            ),
        ),
    ]
