# Generated by Django 5.2.1 on 2025-06-15 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="interest",
        ),
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "home"), (1, "kakao"), (2, "naver"), (3, "google")],
                default=0,
                verbose_name="제공자",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "admin"), (1, "user"), (2, "leader")],
                default=1,
                verbose_name="권한",
            ),
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="options.interest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "유저 관심사",
                "verbose_name_plural": "유저 관심사 목록",
                "db_table": "user_interest",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(
                related_name="users_with_interest",
                through="user.UserInterest",
                to="options.interest",
            ),
        ),
    ]
