# Generated by Django 5.2.1 on 2025-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_interest_alter_user_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(null=True, verbose_name="계정 삭제 날짜"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="계정 삭제 여부"),
        ),
    ]
