# Generated by Django 5.2.1 on 2025-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_deleted_at_user_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="이름"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="닉네임"
            ),
        ),
    ]
