# Generated by Django 5.2.1 on 2025-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_email_alter_user_name_alter_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="introduction",
            field=models.TextField(blank=True, null=True, verbose_name="소개"),
        ),
    ]
