name: "🧹 Chore"
description: "기능과 직접 관련 없는 유지보수 작업"
labels: ["chore"]
body:
  - type: textarea
    attributes:
      label: 📄 작업 설명
      description: 어떤 유지보수 작업인지 설명해주세요.
      placeholder: 예) black, ruff, isort 설정 통합
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업 항목
      description: 작업 내용을 체크박스로 나눠주세요.
      placeholder: |
        - [ ] 코드 정리
        - [ ] CI 설정 수정
        - [ ] 의존성 업데이트
