# Generated by Django 5.2.1 on 2025-06-11 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("options", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetApply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일자"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
                ("max_people", models.IntegerField(blank=True, null=True)),
                ("current_people", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("모집중", "모집중"), ("마감", "마감")],
                        default="모집중",
                        max_length=10,
                    ),
                ),
                ("application_deadline", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="options.area",
                    ),
                ),
                (
                    "digital_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="options.digitallevel",
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="options.interest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
