# Generated by Django 5.2.1 on 2025-06-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meet", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meet",
            name="status",
        ),
    ]
