# Generated by Django 5.2.1 on 2025-06-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet", "0003_remove_meet_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="meet",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
