# Generated by Django 5.2.1 on 2025-06-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet", "0004_meet_is_deleted"),
        ("options", "0001_initial"),
        ("upload", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meet",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "모임",
                "verbose_name_plural": "모임 목록",
            },
        ),
        migrations.RemoveField(
            model_name="meet",
            name="interest",
        ),
        migrations.RemoveField(
            model_name="meet",
            name="time",
        ),
        migrations.AddField(
            model_name="meet",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="options.category",
                verbose_name="카테고리",
            ),
        ),
        migrations.AddField(
            model_name="meet",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="끝나는시간"),
        ),
        migrations.AddField(
            model_name="meet",
            name="file",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.file",
                verbose_name="대표이미지",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meet",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="오픈채팅방링크"
            ),
        ),
        migrations.AddField(
            model_name="meet",
            name="session_count",
            field=models.PositiveIntegerField(default=1, verbose_name="모임횟수"),
        ),
        migrations.AddField(
            model_name="meet",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="시작시간"),
        ),
        migrations.AlterField(
            model_name="meet",
            name="application_deadline",
            field=models.DateTimeField(verbose_name="모집마감일"),
        ),
        migrations.AlterField(
            model_name="meet",
            name="area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="options.area",
                verbose_name="지역",
            ),
        ),
        migrations.AlterField(
            model_name="meet",
            name="contact",
            field=models.CharField(
                choices=[
                    ("on-line", "온라인"),
                    ("off-line", "오프라인"),
                    ("on/off-line", "온/오프라인"),
                ],
                default="on-line",
                max_length=50,
                verbose_name="진행방법",
            ),
        ),
        migrations.AlterField(
            model_name="meet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="meet",
            name="current_people",
            field=models.IntegerField(default=0, verbose_name="현재인원"),
        ),
        migrations.AlterField(
            model_name="meet",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="일정"),
        ),
        migrations.AlterField(
            model_name="meet",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="소개"),
        ),
        migrations.AlterField(
            model_name="meet",
            name="digital_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="options.digitallevel",
                verbose_name="디지털난이도",
            ),
        ),
        migrations.AlterField(
            model_name="meet",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제요청"),
        ),
        migrations.AlterField(
            model_name="meet",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="상세주소"
            ),
        ),
        migrations.AlterField(
            model_name="meet",
            name="max_people",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="최대모집인원"
            ),
        ),
        migrations.AlterField(
            model_name="meet",
            name="title",
            field=models.CharField(max_length=100, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="meet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="meet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="리더",
            ),
        ),
        migrations.AlterField(
            model_name="meetapply",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="가입일자"),
        ),
    ]
