# Generated by Django 5.2.1 on 2025-06-18 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet", "0005_alter_meet_options_remove_meet_interest_and_more"),
        ("upload", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meet",
            name="file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.file",
                verbose_name="대표이미지",
            ),
        ),
    ]
