# Generated by Django 5.2.1 on 2025-06-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet", "0006_alter_meet_file"),
        ("upload", "0007_alter_file_file_alter_file_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meet",
            name="file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="upload.file",
                verbose_name="대표이미지",
            ),
        ),
    ]
