# Generated by Django 5.2.1 on 2025-06-03 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        choices=[("file", "Image"), ("file", "File")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "파일",
                "verbose_name_plural": "파일 목록",
                "db_table": "file",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
