# Generated by Django 5.2.1 on 2025-06-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[("image", "Image"), ("file", "File")],
                max_length=10,
                null=True,
            ),
        ),
    ]
