# Generated by Django 5.2.1 on 2025-06-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_alter_file_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="upload/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="file",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="upload/%Y/%m/%d/thumbnails/"
            ),
        ),
    ]
