# Generated by Django 5.2.1 on 2025-06-18 09:54

from django.db import migrations, models

import apps.upload.models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="category",
            field=models.CharField(
                choices=[
                    ("post", "게시글"),
                    ("profile", "프로필"),
                    ("meet", "모임"),
                    ("certificate", "증명서"),
                    ("other", "기타"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=apps.upload.models.upload_to),
        ),
    ]
