# Generated by Django 5.2.1 on 2025-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_alter_file_file_alter_file_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="file",
            name="object_id",
        ),
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[("image", "Image"), ("video", "Video"), ("file", "File")],
                max_length=10,
                null=True,
            ),
        ),
    ]
