# Generated by Django 5.2.1 on 2025-06-05 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0004_remove_file_content_type_remove_file_object_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="upload/thumbnails/%Y/%m/%d/"
            ),
        ),
    ]
