# Generated by Django 5.2.1 on 2025-06-19 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.upload.models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0004_alter_file_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                null=True,
                storage=apps.upload.models.MediaStorage,
                upload_to=apps.upload.models.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
