# Generated by Django 5.2.1 on 2025-06-20 05:50

import apps.upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0005_alter_file_file_alter_file_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.upload.models.MediaStorage,
                upload_to=apps.upload.models.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.upload.models.MediaStorage,
                upload_to=apps.upload.models.thumbnail_upload_to,
            ),
        ),
    ]
