# Generated by Django 5.2.1 on 2025-06-25 08:11

from django.db import migrations, models

import apps.upload.models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0006_file_deleted_at_file_is_deleted_alter_file_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.upload.models.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.upload.models.thumbnail_upload_to
            ),
        ),
    ]
