# Generated by Django 5.2.1 on 2025-06-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0006_alter_file_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="user",
        ),
    ]
