"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# 이메일 보낼 때 SSL 인증서 경로 인식 불가 시 설정
import os
from datetime import timedelta
from pathlib import Path

import certifi
from dotenv import dotenv_values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# dotenv_values 메서드는 env 파일의 경로를 파라미터로 전달 받아 해당 파일을 읽어온 후 Key, Value 형태로 매핑하여 dict로 반환합니다.
ENV = dotenv_values(BASE_DIR / "envs/.env")
# ENV = dotenv_values(BASE_DIR / "envs/.env.prod")  # 배포 환경 테스트

if ENV.get("DJANGO_ENV", "local") == "local":
    os.environ["SSL_CERT_FILE"] = certifi.where()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['13.209.4.19']

# Application definition

DJANGO_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admin",
]

OWN_APPS = [
    "apps.user",
    "apps.upload",
    "apps.options",
    "apps.reviews",
    "apps.leaders",
    "apps.meet",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",  # poetry add djangorestframework-simplejwt
    "rest_framework_simplejwt.token_blacklist",
    "drf_yasg",
]

INSTALLED_APPS = DJANGO_APPS + OWN_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # username, first_name, last_name, email과 비슷한 비밀번호 거부
        "OPTIONS": {
            "user_attributes": ("email", "name")  # 커스텀 유저 모델의 'name' 필드 포함
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # 기본 길이 8자
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # "password", "12345678" 등 일반적인 비밀번호 거부
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # 숫자만으로 구성된 비밀번호 거부
    },
    {
        "NAME": "utils.custom_password_validation.NoKoreanPasswordValidator",  # 한글 입력 거부 커스텀
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 개발 환경에서 사용하는 경로
STATIC_URL = "static/"
STATIC_DIR = BASE_DIR / "static"

STATICFILES_DIRS = [
    STATIC_DIR,
]

# 배포할 때 사용하는 경로
STATIC_ROOT = BASE_DIR / ".static_root"

# Media
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Auth
AUTH_USER_MODEL = "user.User"  # 유저 모델 지정

# REST_FRAMEWORK 설정
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "utils.pagination.CustomPageNumberPagination",
}

# JWT 설정
SIMPLE_JWT = {
    "BLACKLIST_AFTER_ROTATION": True,
    # "ROTATE_REFRESH_TOKENS": True,  # 리프레시 토큰을 사용할 때마다 새로운 리프레시 토큰을 발급. 기본값 False
    "UPDATE_LAST_LOGIN": True,  # 라스트 로그인 활성화
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # It will work instead of the default serializer(TokenObtainPairSerializer).
    "TOKEN_OBTAIN_SERIALIZER": "utils.jwt_serializers.OndaTokenObtainPairSerializer",
    # ...
}

# 소셜로그인에 사용할 url
# FRONTEND_URL = "https://wistar.o-r.kr"
# FRONTEND_URL = "http://localhost:5173"
# 백엔드에서 임시로 테스트
FRONTEND_URL = "http://127.0.0.1:8000/api"

# 자동 슬래시 붙이는 기능 끄기
APPEND_SLASH = False

# 특정앱 스웨거에서 임시로 비활성화
# config.schema.py에서 설정
SWAGGER_EXCLUDED_APPS = [
    # "apps.user.views",
    # "apps.user.oauth_views_test",
]  # 제외할 앱 이름

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT 인증을 위해 다음과 같이 입력하세요: **Bearer &lt;access_token&gt;**",
        }
    },
}
