# Generated by Django 5.2.1 on 2025-06-10 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meet", "0001_initial"),
        ("reviews", "0002_review_meet_alter_review_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["meet"], name="reviews_rev_meet_id_95db07_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "meet"], name="reviews_rev_user_id_e68970_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["-created_at"], name="reviews_rev_created_03e07d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["-rating"], name="reviews_rev_rating_f8028e_idx"
            ),
        ),
    ]
