# Generated by Django 5.2.1 on 2025-06-17 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_area_alter_post_category_and_more"),
        ("upload", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="upload.file"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="upload.file",
            ),
        ),
        migrations.DeleteModel(
            name="File",
        ),
    ]
