# Generated by Django 5.2.1 on 2025-06-18 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupchatmembership",
            name="joined_at",
        ),
        migrations.RemoveField(
            model_name="groupchatmessage",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="groupchatmembership",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="생성일자",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupchatmembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일자"),
        ),
        migrations.AddField(
            model_name="groupchatmessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="생성일자",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupchatmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일자"),
        ),
        migrations.AddField(
            model_name="groupchatroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일자"),
        ),
        migrations.AlterField(
            model_name="groupchatroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일자"),
        ),
    ]
